# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ECODA\Desktop\dhwtest\pyapitest\vscode\uitest.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(696, 355)
        self.swjbtn1 = QtWidgets.QPushButton(Dialog)
        self.swjbtn1.setGeometry(QtCore.QRect(330, 210, 141, 121))
        font = QtGui.QFont()
        font.setFamily("HY견고딕")
        font.setStrikeOut(False)
        self.swjbtn1.setFont(font)
        self.swjbtn1.setAutoFillBackground(False)
        self.swjbtn1.setStyleSheet("")
        self.swjbtn1.setObjectName("swjbtn1")
        self.swjlabel = QtWidgets.QLabel(Dialog)
        self.swjlabel.setGeometry(QtCore.QRect(170, 10, 511, 91))
        font = QtGui.QFont()
        font.setFamily("HY헤드라인M")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.swjlabel.setFont(font)
        self.swjlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.swjlabel.setObjectName("swjlabel")
        self.swjbtn2 = QtWidgets.QPushButton(Dialog)
        self.swjbtn2.setGeometry(QtCore.QRect(510, 220, 111, 23))
        self.swjbtn2.setObjectName("swjbtn2")
        self.swjbtn3 = QtWidgets.QPushButton(Dialog)
        self.swjbtn3.setGeometry(QtCore.QRect(480, 280, 161, 23))
        self.swjbtn3.setObjectName("swjbtn3")
        self.swjpbar = QtWidgets.QProgressBar(Dialog)
        self.swjpbar.setGeometry(QtCore.QRect(170, 110, 481, 41))
        self.swjpbar.setProperty("value", 0)
        self.swjpbar.setObjectName("swjpbar")
        self.testbtn = QtWidgets.QPushButton(Dialog)
        self.testbtn.setGeometry(QtCore.QRect(190, 300, 101, 23))
        self.testbtn.setObjectName("testbtn")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(180, 220, 120, 80))
        self.groupBox.setObjectName("groupBox")
        self.swjdate = QtWidgets.QDateEdit(self.groupBox)
        self.swjdate.setGeometry(QtCore.QRect(20, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.swjdate.setFont(font)
        self.swjdate.setObjectName("swjdate")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(10, 30, 141, 301))
        self.listWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.listWidget.setTabKeyNavigation(False)
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.swjbtn1.setText(_translate("Dialog", "기상청 데이터\n"
"받아오기"))
        self.swjlabel.setText(_translate("Dialog", "swjlabel"))
        self.swjbtn2.setText(_translate("Dialog", "EPW파일생성"))
        self.swjbtn3.setText(_translate("Dialog", "기상데이터만 별도저장"))
        self.testbtn.setText(_translate("Dialog", "연도설정TEST"))
        self.groupBox.setTitle(_translate("Dialog", "희망 연도 설정"))
        self.swjdate.setDisplayFormat(_translate("Dialog", "yyyy"))
